name: ci
on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Tests
        run: go test -cover ./...
        env:
          GOFLAGS: -mod=vendor

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...
        env:
          GOFLAGS: -mod=vendor

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install linter
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check style
        run: test -z $(go fmt ./...)
        env:
          GOFLAGS: -mod=vendor

      - name: Run linter
        run: staticcheck ./...
        env:
          GOFLAGS: -mod=vendor
